log_format: console
no_color: false
package:
  oci_concurrency: 15
  create:
    set:
      version: v0.0.0-k0s.0
      # renovate: datasource=github-releases depName=k0sproject/k0s versioning=regex:^v(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)\+k0s\.(?<build>\d+)$
      k0s_version: v1.35.3+k0s.0
      k0s_sha_amd64: 918003c3f68107cb330f62be3835ff70c2699fefc9b6b49ad039493839d5d3ee
      k0s_sha_arm64: 721e0294345c10373564a8859c635dffd9aac1bfa311c7b3b29bffdc25a5f97e
      # renovate: datasource=github-releases depName=k0sproject/k0sctl versioning=regex:^v(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)$
      k0sctl_version: v0.29.0
      k0sctl_sha_amd64: 37bfa438cacffeefe2777c09d00f834665a4b8a57d41b4fe28fbd3804e4166a2
      k0sctl_sha_arm64: 7c8836897de2db83ff35636f40e2f7de288fc164229da35aa1cb883d6f5e8293
      # renovate: datasource=docker depName=quay.io/cilium/charts/cilium versioning=regex:^v?(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)$
      cilium_chart_version: 1.19.3
      # renovate: datasource=github-releases depName=cilium/cilium-cli versioning=regex:^v(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)$
      cilium_cli_version: v0.19.2
