log_format: console
no_color: false
package:
  oci_concurrency: 15
  create:
    set:
      version: v0.0.0-k0s.0
      # renovate: datasource=github-releases depName=k0sproject/k0s versioning=regex:^v(?<major>1)\.(?<minor>32)\.(?<patch>\d+)\+k0s\.(?<build>\d+)$
      k0s_version: v1.32.8+k0s.0
      k0s_sha_amd64: ecca8e04c966f71d41543f8e9568768d73cd886b97c3911b6d2b205aa6452c38
      k0s_sha_arm64: fd30aa250ae5b5077ebc312287618d2055df31d978412c1e611181de90448a04
      # renovate: datasource=github-releases depName=k0sproject/k0sctl versioning=regex:^v(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)$
      k0sctl_version: v0.27.0
      k0sctl_sha_amd64: 54acd2c8feb98821cc8c541ec4a0a151478997f34e1a3f9d3dec7a4369712ca9
      k0sctl_sha_arm64: c8ba1738fafd75eb97ebad8cbcaa2dc44d702417be18245e8bae735f4a86e82c
